### PR TITLE
fix player allowed to continue looting if crate is still open while extracting

### PR DESCRIPTION
**Pull request by Beat2er**

### CODE REVIEW

**Comment by Beat2er** [comment]
same as ExitWhileLootingPatch in SPT-AKI

**Comment by mihaicm93** [comment]
There was a fix for this alread, a few hours ago, I see you have it implemented differently
https://github.com/stayintarkov/StayInTarkov.Client/pull/217

**Comment by Beat2er** [comment]
> There was a fix for this alread, a few hours ago, I see you have it implemented differently #217

No, this has nothing to do with the airdrop fix, It just fixes the behaviour that players keep their invenotry/crate inventories open after extracted. This allows for further looting and I see this as unintentional

**Comment by mihaicm93** [comment]
Yup I see now, sorry

**Review by mihaicm93 — APPROVED** [review]

**Pull request merged**
