### PR TITLE
Fixed disabling SCAV-Mode

### PR DESCRIPTION
**Pull request by TehFl0w**
Fixed disabling SCAV-Mode and moved PMC object to center, may need additional logic on resolutions other than 1080p

grafik

### CODE REVIEW

**Review by trippyone — CHANGES_REQUESTED** [review]
it is not centered in 2K.

image

**Comment by TehFl0w** [comment]
Yeah I already noticed it while moving/scaling windows around, I'll think about something

**Review by trippyone — DISMISSED** [review]
Unfortunately same results.

image

**Comment by Lacyway** [comment]
Get the parent Canvas Group transform instead and use that to scale it with math.
Can you try this on different resolutions?

```csharp
var mmSSC = pmcs.transform.parent.gameObject;

pmcs.transform.position = new Vector3(mmSSC.transform.position.x / 1.305f, pmcs.transform.position.y * 0.75f, 0);
```

**Comment by ArchangelWTF** [comment]
That scaling seems to do the trick, the selection for it stays nicely in the middle now. (Tested at 720, 1080, 1440, 4k)

**Comment by Lacyway** [comment]
> That scaling seems to do the trick, the selection for it stays nicely in the middle now. (Tested at 720, 1080, 1440, 4k)

I have tested it as well on 16:9 and 4:3, seems to always be fine.
@trippyone will you try and approve PR?

**Review by Lacyway — APPROVED** [review]

**Pull request merged**
